version: '3'

services:
  traefik:
    image: traefik:v3.2
    networks:
      - traefiknetwork
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DOMAIN_NAME}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_BASIC_AUTH_USERS}"
      - "traefik.http.routers.dashboard.tls=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.prod.yaml:/traefik.yaml:ro
      - ./config/config.prod.yaml:/config.yaml:ro
      - ./certs:/etc/certs:ro
      - ./certs/acme.json:/acme.json
      - /var/log/traefik:/var/log
    restart: unless-stopped

networks:
    traefiknetwork:
        name: traefiknetwork
        external: true